abstract: Container class for currency conversion/formatting
author: Christopher H. Laco
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Data-Currency
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Grouped: 0.03
  Class::Inspector: 0
  Finance::Currency::Convert::WebserviceX: 0.03
  Locale::Currency: 2.07
  Locale::Currency::Format: 1.22
  Scalar::Util: 0
  perl: 5.8.1
tests: t/*.t
version: 0.04000
